### ISSUE TITLE
Dashboard Screen

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#20]
A screen to display as an entry point to the application.

## User Story:

As a user, I want to see a dashboard with relevant content so I can quickly and easily interact how I need to.

## Tasks:

- [x] scan a new thing button
- [x] listing of nearby things to guess
- [ ] listing of nearby players 
- [ ] listing of friends
