### ISSUE TITLE
Scan Screen

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#21]
A screen to use the device camera to identify something and capture its image.

## User Story:

As a user, I want to be able to quickly take a picture of something to have clues auto-generated for the game.

## Tasks:

- [x] define shared interface and ui
- [x] integrate android camera
- [ ] integrate ios camera
- [ ] integrate machine learning vision analyzers
- [ ] generate clues and decide best ones
