### ISSUE TITLE
Clue Analyzers

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#22]
When a camera or image is active be able to generate clues about it for the game.

## User Story:

As a user, I want clues about images in the game to be accurate, relavant, helpful, fun, and easy to use.

## Tasks:

- [ ] integrate machine vision overall labeling
- [ ] integrate machine vision object detection and labelling
- [ ] integrate machine vision segmentation
- [ ] integrate machine vision vector embeddings
- [ ] integrate overal color analysis
- [ ] integrate segmentation color analysis
- [ ] integrate rhyming of labels
