### ISSUE TITLE
Guess Screen

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#23]
A screen to use the camera to try and guess an image based upon its generated clues.

## User Story:

As a user, I want to guess things that other players have scanned for points.

## Tasks:

- [] reuse scan camera and clue analyzers
- [] define logic to match clues
- [] give player UI indicators while guessing
