### ISSUE TITLE
Scanning People

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#26]
Scanning people should be functionality that is optional for a user.  When enabled it adds additional clues and the ability for a more social aspect (though we wont use the dating word).

## User Story 1:

As a user, I don't want my privacy protected and my self image not publicly viewable.

## User Story 2:

As a user, I want to let people guess who I am to meet them.

## Tasks:

- [] feature based functionality (variants, store add-on)
- [] additional face clues
- [] additional name clues (lookup)
- [] additional post to social profiles (who is this??)
- [] sentiment / body language clues
