### ISSUE TITLE
Location Services

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#27]
Location services must run to identify point-in-time locations of players and things.

## User Story:

As a user, I want to know what things are nearby so that I can interact with them.

## Tasks:

- [x]  local location service per screen
- [ ]  local background location service
- [ ] remote location subscriptions
- [ ] geofencing
