### ISSUE TITLE
Sponsorship support

### ISSUE THREAD

**Issue by ryjen** [hackelia-micrantha/skouter#52]
## User Story

I want to support the project by donating or sponsoring

## Details

To better support value for sponsorship am considering closing source to some application features.

It would be ideal to to have the public main branch contain interfaces and a library of the implementation.

Sponsorship would then allow access to the private branch or repo with with implementations.

## Tasks

- [ ] move bluebell into a separate repo
- [ ] import bluebell via submodule or apk
- [ ] move architecture layers into repos (data, domain, platform, ui)
- [ ] import architecture layers via submodule or apk
